version: '3'

services:
  db:
    image: postgres:13
    container_name: db1
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: worker
      POSTGRES_PASSWORD: worker
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U worker -d app"]
      interval: 1s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
    container_name: web
    ports:
      - "8000:8000"
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy  
    environment:
      DJANGO_DB_HOST: db
      DJANGO_DB_NAME: app
      DJANGO_DB_USER: worker
      DJANGO_DB_PASS: worker
      DJANGO_DB_PORT: "5432"
      DJANGO_DEBUG: "False"
    volumes:
      - .:/app
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
volumes:
  postgres_data: